import { invoke } from '@tauri-apps/api/core'
import type { Attachment, Folder, Mode, Note, NotePatch, NoteSummary, Project, Settings, Version, View } from '../types'

export const api = {
  projects: () => invoke<Project[]>('list_projects'),
  upsertProject: (input: { id?: string; name: string; description: string; color: string; icon: string }) => invoke<Project>('upsert_project', { input }),
  projectState: (id: string, action: string) => invoke<void>('set_project_state', { id, action }),
  reorderProjects: (ids: string[]) => invoke<void>('reorder_projects', { ids }),
  folders: () => invoke<Folder[]>('list_folders'),
  upsertFolder: (input: { id?: string; projectId: string; name: string }) => invoke<Folder>('upsert_folder', { input }),
  folderState: (id: string, deleted: boolean) => invoke<void>('set_folder_state', { id, deleted }),
  reorderFolders: (ids: string[]) => invoke<void>('reorder_folders', { ids }),
  newNote: (projectId: string | null, folderId: string | null) => invoke<Note>('new_note', { projectId, folderId }),
  note: (id: string) => invoke<Note>('get_note', { id }),
  saveNote: (patch: NotePatch) => invoke<Note>('save_note', { patch }),
  notes: (view: View, targetId: string | null, offset = 0) => invoke<NoteSummary[]>('list_notes', { view, targetId, offset }),
  search: (query: string) => invoke<NoteSummary[]>('search_notes', { query }),
  noteState: (id: string, action: string) => invoke<void>('set_note_state', { id, action }),
  emptyTrash: () => invoke<void>('empty_trash'),
  tags: (noteId: string) => invoke<string[]>('get_tags', { noteId }),
  setTags: (noteId: string, names: string[]) => invoke<void>('set_tags', { noteId, names }),
  versions: (noteId: string) => invoke<Version[]>('list_versions', { noteId }),
  restoreVersion: (versionId: string) => invoke<Note>('restore_version', { versionId }),
  attachments: (noteId: string) => invoke<Attachment[]>('list_attachments', { noteId }),
  importAttachment: (noteId: string, filename: string, data: number[]) => invoke<Attachment>('import_attachment', { noteId, filename, data }),
  importAttachmentPath: (noteId: string, path: string) => invoke<Attachment>('import_attachment_path', { noteId, path }),
  deleteAttachment: (id: string) => invoke<void>('delete_attachment', { id }),
  startAttachmentDrag: (id: string) => invoke<void>('start_attachment_drag', { id }),
  settings: () => invoke<Settings>('get_settings'),
  setSetting: (key: string, value: string) => invoke<void>('set_setting', { key, value }),
  dataDirectory: () => invoke<string>('data_directory'),
  backup: (destination?: string) => invoke<string>('create_backup', { destination: destination ?? null }),
  autoBackupIfDue: () => invoke<void>('auto_backup_if_due'),
  exportProject: (projectId: string, destination: string) => invoke<void>('export_project', { projectId, destination }),
  restoreBackup: (source: string) => invoke<void>('restore_backup', { source }),
  exportFile: (path: string, content: string) => invoke<void>('export_note_file', { path, content }),
  importText: (path: string, projectId: string | null) => invoke<Note>('import_text_note', { path, projectId }),
  setMode: (mode: string) => invoke<void>('set_window_mode', { mode }),
  mode: () => invoke<Mode>('get_window_mode'),
  showProjects: (selectedId: string | null) => invoke<void>('show_projects', {selectedId}),
  hideProjects: () => invoke<void>('hide_projects'),
  isAppFocused: () => invoke<boolean>('is_app_focused'),
  showDialog: (kind: 'project' | 'folder' | 'versions', id?: string, projectId?: string) => invoke<void>('show_dialog', { kind, id: id ?? null, projectId: projectId ?? null }),
  hideDialog: () => invoke<void>('hide_dialog'),
  quit: () => invoke<void>('quit_app'),
  reportError: (message: string) => invoke<void>('report_error', { message }),
}
